trigger:
- master

resources:
- repo: self

variables:
  subscription: 'Visual Studio Enterprise'
  acrName: 'ttacroqsodrhmexw6s'
  resourceGroup: 'tt-test'
  helmfrom: 'Deploy'

jobs:
# - job: Deploy_Scripts
#   pool:
#     vmImage: 'ubuntu-16.04'
#   steps:
#   - task: CopyFiles@2
#     displayName: Copy release scripts
#     inputs:
#       SourceFolder: '$(helmfrom)'
#       Contents: '**'
#       TargetFolder: '$(Build.ArtifactStagingDirectory)'
#   - task: PublishBuildArtifacts@1
#     displayName: Publish scripts artifact
#     inputs:
#       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#       ArtifactName: 'helm'
#       publishLocation: 'Container'
# - job: Build_Linux
#   pool:
#     vmImage: 'ubuntu-16.04'
#   steps:
#   - task: AzureCLI@1
#     displayName: Build and Push to ACR 
#     inputs:
#       azureSubscription: '${{ variables[''subscription''] }}'
#       scriptLocation: 'inlineScript'
#       inlineScript: 'pwsh -File Build-Push.ps1 -resourceGroup $(resourceGroup) -acrName $(acrName) -dockerTag $(Build.BuildId)'
#       addSpnToEnvironment: true
#       useGlobalConfig: true
#       workingDirectory: 'Deploy'
- job: Build_Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: AzureCLI@1
    displayName: Build and Push to ACR 
    inputs:
      azureSubscription: '${{ variables[''subscription''] }}'
      scriptLocation: 'inlineScript'
      inlineScript: 'pwsh -File Build-Push.ps1 -resourceGroup $(resourceGroup) -acrName $(acrName) -dockerTag $(Build.BuildId) -isWindowsMachine 1'
      addSpnToEnvironment: true
      useGlobalConfig: true
      workingDirectory: 'Deploy'