trigger:
- master

resources:
- repo: self

variables:
  acrName: 'ttacroqsodrhmexw6s'
  resourceGroup: 'tt-test'
  helmfrom: 'Deploy'

jobs:
- job: Build_Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Visual Studio Enterprise'
      scriptLocation: 'inlineScript'
      inlineScript: 'Build-Push.ps1 -resourceGroup $(resourceGroup) -acrName $(acrName)'
      workingDirectory: 'Deploy'
  - task: CopyFiles@2
    inputs:
      sourceFolder: ${{ variables['helmfrom'] }}
      targetFolder: ${{ variables['Build.ArtifactStagingDirectory'] }}
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ${{ variables['Build.ArtifactStagingDirectory'] }}
      artifactName: helm