trigger:
- master

resources:
- repo: self

variables:
  subscription: 'Visual Studio Enterprise'
  acrName: 'ttacroqsodrhmexw6s'
  resourceGroup: 'tt-test'
  helmfrom: 'Deploy'

jobs:
- job: Build_Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: AzureCLI@1
    displayName: 'Get credentials'
    inputs:
      azureSubscription: '${{ variables[''subscription''] }}'
      scriptLocation: inlineScript
      inlineScript: 'az aks get-credentials -n tailwindtradersaksoqsodrhmexw6s -g $(resourceGroup)'
      addSpnToEnvironment: true
      useGlobalConfig: true
      workingDirectory: '$(System.ArtifactsDirectory)\helm'
  - task: AzureCLI@1
    displayName: Create Secrets 
    inputs:
      azureSubscription: '${{ variables[''subscription''] }}'
      scriptLocation: 'inlineScript'
      inlineScript: 'pwsh -File Create-Secret.ps1 -resourceGroup $(resourceGroup) -acrName $(acrName)'
      addSpnToEnvironment: true
      useGlobalConfig: true
      workingDirectory: 'Deploy'
  - task: AzureCLI@1
    displayName: Build and Push to ACR 
    inputs:
      azureSubscription: '${{ variables[''subscription''] }}'
      scriptLocation: 'inlineScript'
      inlineScript: 'pwsh -File Build-Push.ps1 -resourceGroup $(resourceGroup) -acrName $(acrName) -dockerTag $(Build.BuildId)'
      addSpnToEnvironment: true
      useGlobalConfig: true
      workingDirectory: 'Deploy'
  - task: CopyFiles@2
    displayName: Copy release scripts
    inputs:
      SourceFolder: '$(helmfrom)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: Publish scripts artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'helm'
      publishLocation: 'Container'



      variables:
  ResourceGroup: 'tt-test'
