trigger:
- master

resources:
- repo: self

variables:
  registryEndpoint: 'ttacroqsodrhmexw6s'
  helmfrom: 'Deploy'

jobs:
- job: Build_Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DockerCompose@0
    displayName: Compose build
    inputs:
      dockerComposeCommand: 'build'
      containerregistrytype: Azure Container Registry
      azureSubscriptionEndpoint: Visual Studio Enterprise – MPN
      azureContainerRegistry: ${{ variables['registryEndpoint'] }}
      dockerComposeFile: Source/docker-compose.yml
      additionalDockerComposeFiles: docker-compose.override.yml
      qualifyImageNames: true
      projectName: "tailwindtraders"
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.BuildId'] }}
  - task: DockerCompose@0
    displayName: Compose push
    inputs:
      action: Push services
      dockerComposeCommand: 'push'
      containerregistrytype: Azure Container Registry
      azureSubscriptionEndpoint: Visual Studio Enterprise – MPN
      azureContainerRegistry: ${{ variables['registryEndpoint'] }}
      dockerComposeFile: Source/docker-compose.yml
      additionalDockerComposeFiles: docker-compose.override.yml
      qualifyImageNames: true
      projectName: "tailwindtraders"
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.BuildId'] }} 
  - task: CopyFiles@2
    inputs:
      sourceFolder: ${{ variables['helmfrom'] }}
      targetFolder: ${{ variables['Build.ArtifactStagingDirectory'] }}
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ${{ variables['Build.ArtifactStagingDirectory'] }}
      artifactName: helm