replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/webapigw.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsights__InstrumentationKey
    - name: PopularProductsApiUrl
    - name: ProductsApiUrl
    - name: ProfileApiUrl
    - name: LoginApiUrl
    - name: CouponsApiUrl
    - name: ImageClassifierApiUrl
    - name: StockApiUrl
    - name: ISSUER
    - name: SECURITYKEY
    - name: UseB2C
    - name: B2CIssuer
    - name: Authority
    - name: RegisterUsers
    - name: RegistrationUsersEndpoint
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: UseMlNetClassifier
      value: "true"
