# Global values for all helm charts. See comments for usage

inf:
  sa: ttsa
  db:
    products:
      host: ***REMOVED***
      port: "1433"
      catalog: Products
      user: ***REMOVED***
      pwd: ***REMOVED***
    profile:
      host: ***REMOVED***
      port: "1433"
      catalog: Profile
      user: ***REMOVED***
      pwd: ***REMOVED***
    coupons:
      user: ttcosmosdbneajthzpxpysw
      pwd: ***REMOVED***
      host: ttcosmosdbneajthzpxpysw.documents.azure.com
      port: "10255"
      dbName: Coupons
      constr: ttcosmosdbneajthzpxpysw:***REMOVED***@ttcosmosdbneajthzpxpysw.documents.azure.com:10255/Coupons/?ssl=true&replicaSet=globaldb
      collection: CouponCollection   
    popularproducts:
      host: ***REMOVED***
      port: "1433"
      catalog: PopularProducts
      user: ***REMOVED***
      pwd: ***REMOVED***
    cart:
      host: ***REMOVED***
      auth: ***REMOVED***
  storage:
    productimages: ***REMOVED***/product-list
    productdetailimages: ***REMOVED***/product-detail
    couponimage: ***REMOVED***/coupon-list
    profileimages: ***REMOVED***/profiles-list
  appinsights:
    id: ""
  ingress:
    products:
      path: /product-api
    profile:
      path: /profile-api
    coupons:
      path: /coupons-api
    popularproducts:
      path: /popular-products-api
    stock:
      path: /stock-api
    imageclassifier:
      path: /image-classifier-api
    mobilebff:
      path: /mobilebff
    webbff:
      path: /webbff    
    cart:
      path: /cart-api
  apiurls:
    popularproductsapiurl: http://popularproducts
    productsapiurl: http://product 
    profileapiurl: http://profile
    couponsapiurl: http://coupons
    stockapiurl: http://stock
    imageclassifierapiurl: http://imageclassifier

az:
  productvisitsurl: ""

# Shared ingress configurations
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
#  hosts:
#    - HOST_DOMAIN (i. e. <guid>.<region>.aksapp.io). Set by the installation script

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
