# Global values for all helm charts. See comments for usage

inf:
  sa: ttsa
  db:
    products:
      host: # DB HOST LIKE tailwindtradersserver-dev.database.windows.net
      port: "1433"
      catalog: # DB NAME LIKE  Microsoft.Tailwind.Products-dev
      user: # ADMIN USERNAME LIKE tailadmin
      pwd: # ADMIN PWD
    profile:
      host: # DB HOST LIKE tailwindtradersserver-dev.database.windows.net
      port: "1433"
      catalog: # DB NAME LIKE  Microsoft.Tailwind.Profile-dev
      user: # ADMIN USERNAME LIKE tailadmin
      pwd: # ADMIN PWD
    coupons:
      user: # COSMOS USER tailwindtraders-coupons-dev
      pwd: # COSMOS PWD 
      host: # COSMOS HOST LIKE tailwindtraders-coupons-dev.documents.azure.com
      port: "10255"
      dbName: Coupon
      constr: # COSMOS CONSTR
      collection: CouponCollection   
    popularproducts:
      host: # DB HOST LIKEtailwindtradersserver-dev.database.windows.net
      port: "1433"
      catalog: # DB NAME LIKE  Microsoft.Tailwind.PopularProduct-dev
      user: # ADMIN USERNAME LIKE tailadmin
      pwd: # ADMIN PWD  
    cart:
      host: # COMSOS HOST FOR THE CART like https://ttwebbasket-dev.documents.azure.com:443/
      auth: # COSMOS AUTH KEY
  storage:
    productimages: #URL-OF-STORAGE/product-list
    productdetailimages: #URL-OF-STORAGE/product-detail
    couponimage: #URL-OF-STORAGE/coupon-list
    profileimages: #URL-OF-STORAGE/profiles-list
  appinsights:
    id: ""
  ingress:
    products:
      path: /product-api
    profile:
      path: /profile-api
    coupons:
      path: /coupons-api
    popularproducts:
      path: /popular-products-api
    stock:
      path: /stock-api
    imageclassifier:
      path: /image-classifier-api
    mobilebff:
      path: /mobilebff
    webbff:
      path: /webbff    
    cart:
      path: /cart-api
  apiurls:
    popularproductsapiurl: http://popularproducts
    productsapiurl: http://product 
    profileapiurl: http://profile
    couponsapiurl: http://coupons
    stockapiurl: http://stock
    imageclassifierapiurl: http://imageclassifier

az:
  productvisitsurl: ""

# Shared ingress configurations
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
#  hosts:
#    - <guid>.<region>.aksapp.io   # NOT NEEDED. SET BY SCRIPTS

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

sec:
  issuer: TTFakeLogin
  securityKey: nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB