trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  resourceGroup: 'tt-test'
  acrName: 'ttacroqsodrhmexw6s'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PowerShell@2
      displayName: 'az login'
      inputs:
        targetType: 'InlineScript'
        script: |
          az login -u $(username) -p $(password)
          az account set --subscription $(subscriptionId)
    - task: PowerShell@2
      displayName: 'Create-Secret'
      inputs:
        filePath: '$(Build.SourcesDirectory)/Deploy/Create-Secret.ps1'
        arguments: '-resourceGroup $(resourceGroup) -acrName $(acrName)'
        workingDirectory: '$(Build.SourcesDirectory)/Deploy'
    - task: PowerShell@2
      displayName: 'Build-Push'
      inputs:
        filePath: '$(Build.SourcesDirectory)/Deploy/Build-Push.ps1'
        arguments: '-resourceGroup $(resourceGroup) -acrName $(acrName) -dockerTag $(tag)'
        workingDirectory: '$(Build.SourcesDirectory)/Deploy'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/Deploy'
        artifactName: 'scripts'
        publishLocation: 'Container'