trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  resourceGroup: 'tt-test'
  acrName: 'ttacroqsodrhmexw6s'
  username: 'cmiguel@plainconcepts.com'
  password: '4Mx+66k{'
  subscriptionId: 'a60f4ee6-1370-4ef3-8ebf-7e0e7751f250'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@1
      displayName: 'az login'
      inputs:
        azureSubscription: 'Visual Studio Enterprise – MPN'
        scriptLocation: 'inlineScript'
        inlineScript: 'az login -u $(username) -p "$(password)"'
    - task: AzureCLI@1
      displayName: 'az login'
      inputs:
        azureSubscription: 'Visual Studio Enterprise – MPN'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account --subscription $(subscriptionId)'
    - task: PowerShell@2
      displayName: 'Create-Secret'
      inputs:
        filePath: '$(Build.SourcesDirectory)/Deploy/Create-Secret.ps1'
        arguments: '-resourceGroup $(resourceGroup) -acrName $(acrName)'
        workingDirectory: '$(Build.SourcesDirectory)/Deploy'
    - task: PowerShell@2
      displayName: 'Build-Push'
      inputs:
        filePath: '$(Build.SourcesDirectory)/Deploy/Build-Push.ps1'
        arguments: '-resourceGroup $(resourceGroup) -acrName $(acrName) -dockerTag $(tag)'
        workingDirectory: '$(Build.SourcesDirectory)/Deploy'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/Deploy'
        artifactName: 'scripts'
        publishLocation: 'Container'