coupon.api:
  image: coupon.api:latest
  container_name: coupon-node
  build:
    context: .
    dockerfile: Services/Tailwind.Traders.Coupon.Api/Dockerfile
  environment:
    - CONNECTIONSTRING=127.0.0.1:27017/CouponsDb
    - PORT=27017
    - COUPON_COLLECTION=CouponCollection
    - URL_BASE=
    - ISSUER=TTFakeLogin
    - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
  ports:
    - "5002:3000"