version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  nosql.data:
    ports:
      - "27017:27017"

  cart-cosmosdb:
    ports:
      - "8081:8081"

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.TailWindTraders.Product;User Id=sa;Password=Pass@word
      - ProductImagesUrl=
      - ProductDetailImagesUrl=
      - ProductVisitsUrl=
    ports:
      - "5000:80"   

  profile.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.TailWindTraders.Profile;User Id=sa;Password=Pass@word
      - ProfilesImageUrl=
    ports:
      - "5001:80"
      
  coupon.api:
    environment:
      - CONNECTIONSTRING=127.0.0.1:27017/CouponsDb
      - PORT=27017
      - COUPON_COLLECTION=CouponCollection
      - URL_BASE=
    ports:
      - "5002:3000"

  popular-product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=localhost;Port=5433;User Id=sa;Password=Pass@word;Database=Microsoft.TailWindTraders.PopularProduct;
      - AzureStorageUrl=
    ports:
      - "5003:80"
      
  stock.api:
    ports:
      - "5004:80"  

  product-visits.function:
    environment:
      - CONNECTIONSTRING=127.0.0.1:27017/ProductVisitsDb
      - VISITCOLLECTION=ProductVisitsCollection
    ports:
      - "5005:3000"

  image-classifier.api:
    environment:
      - ImagePath=/imguploads
    ports:
      - "5006:80"

  cart.api:
    environment:
      - HOST=https://10.0.75.1:8081
      - AUTHKEY=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==  # Emulator AUTHKEY
    ports:
      - "5007:3001"      

  mobileapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PopularProductsApiUrl=http://popular-product.api
      - ProductsApiUrl=http://product.api
      - ProfileApiUrl=http://profile.api
      - CouponsApiUrl=http://coupon.api
      - ImageClassifierApiUrl=http://image-classifier.api
    ports:
      - "5100:80"

  webapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PopularProductsApiUrl=http://popular-product.api
      - ProductsApiUrl=http://product.api
      - ProfileApiUrl=http://profile.api
      - CouponsApiUrl=http://coupon.api
      - ImageClassifierApiUrl=http://image-classifier.api
    ports:
      - "5200:80"