version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  nosql.data:
    ports:
      - "27017:27017"

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.TailWindTraders.Product;User Id=sa;Password=Pass@word
     - ProductVisitsUrl=
    ports:
      - "5000:80"   

  profile.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.TailWindTraders.Profile;User Id=sa;Password=Pass@word
      - ProfilesImageUrl=
      - SecurityKey=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - Issuer=TTFakeLogin
    ports:
      - "5001:80"

  login.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.TailWindTraders.Profile;User Id=sa;Password=Pass@word
      - ProfilesImageUrl=
      - SecurityKey=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - Issuer=TTFakeLogin
    ports:
      - "5008:80"
      
  coupon.api:
    environment:
      - CONNECTIONSTRING=nosql.data:27017/CouponsDb
      - PORT=3000
      - COUPON_COLLECTION=CouponCollection
      - URL_BASE=nosql.data:27017/CouponsDb
      - ISSUER=TTFakeLogin
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
    ports:
      - "5002:3000"
      
  popular-product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.TailWindTraders.PopularProduct;User Id=sa;Password=Pass@word
      - Issuer=TTFakeLogin
      - SecurityKey=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - AzureStorageUrl=
    ports:
      - "5003:80"
      
  stock.api:
    ports:
      - "5004:80"  

  product-visits.function:
    environment:
      - CONNECTIONSTRING=127.0.0.1:27017/ProductVisitsDb
      - VISITCOLLECTION=ProductVisitsCollection
    ports:
      - "5005:3000"

  image-classifier.api:
    environment:
      - ImagePath=/imguploads
      - ISSUER=TTFakeLogin
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
    ports:
      - "5006:80"

  cart.api:
    environment:
      - HOST=${COSMOSDB_HOST:-https://10.0.75.1:8081}   # Emulator URI
      - AUTHKEY=${COSMOSDB_AUTHKEY}  
      - ISSUER=TTFakeLogin
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
    ports:
      - "5007:3001"      

  mobileapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PopularProductsApiUrl=http://popular-product.api
      - ProductsApiUrl=http://product.api
      - ProfileApiUrl=http://profile.api
      - CouponsApiUrl=http://coupon.api
      - ImageClassifierApiUrl=http://image-classifier.api
      - LoginApiUrl=http://login.api
    ports:
      - "5100:80"

  webapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PopularProductsApiUrl=http://popular-product.api
      - ProductsApiUrl=http://product.api
      - ProfileApiUrl=http://profile.api
      - LoginApiUrl=http://login.api
      - CouponsApiUrl=http://coupon.api:3000
      - ImageClassifierApiUrl=http://image-classifier.api
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - ISSUER=TTFakeLogin
      - UseMlNetClassifier=true
    ports:
      - "5200:80"